[font]
normal = { family = "FiraCode Nerd Font Mono"}
# size = 12.25

# [terminal.shell]
# program = "tmux"

[general]
import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[window]
decorations = "none"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[window.padding]
x = 25 
y = 25
