[font.normal]
family = "FiraCode Nerd Font Mono"

# [terminal.shell]
# program = "tmux"

[general]
import = [
    "~/.config/alacritty/themes/themes/base16_default_dark.toml"
]

[window]
decorations = "none"

[window.padding]
x = 25 
y = 25

[env]
term = "xterm-256color"
